---
prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    ingress:
      enabled: true
      path: /prometheus
      hosts:
        - "monitoring-educates-cli-w01-s002.172.20.10.2.nip.io"
    extraFlags:
      - web.external-url=/prometheus/
    persistentVolume:
      enabled: false
