---
alertmanager:
  ingress:
    enabled: true
    hosts:
      - host: ""
        paths:
          - path: /alertmanager
            pathType: ImplementationSpecific
  persistence:
    enabled: false
